# meta
author:
    name: Munir Hussin
    url: https://profound7.github.io
    github: profound7
    twitter: profound7
    disqus: profound7
    analytics: UA-25251488-4

meta:
    categories:
        - Dev
        - Comics
        - Movies
    tags:
        - Haxe
        - Macro
        - JavaScript
        - Math
        - Cross Platform

# setup
gems:
    - jekyll-paginate
    - jekyll-mentions

excerpt_separator: <!--more-->
permalink: /blog/:categories/:slug/
paginate: 5
paginate_path: '/blog/page:num/'

timezone: Asia/Singapore

markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    auto_id_stripping: true
    parse_block_html: true
